Страница записи на оказание тех. услуг
CyberDAS-Dev/Frontend pull request #85
Opened 2021-09-06 13:51 UTC by idonotknowwhoiam

Необходимо написать инструкцию по использованию в алерт и подключить к апи.
Вынес карточку кнопку в отдельной компонент, для более удобного использования, сам компонент построен на карточке бутстрапа.

2021-09-06 22:43 UTC, qqpayne commented on src/forms/Techical.jsx
> +    corpus: yup.number().required().nullable(),
А почему он nullable?

2021-09-06 22:47 UTC, qqpayne commented on src/forms/Techical.jsx
> +                        style={{ height: '200px' }}
Давай лучше вместо фиксированный высоты попробуем проставить `rows`.  Правда, для этого придется немного извернуться и, возможно, получится не очень.

Вот здесь есть пример: https://react-bootstrap.github.io/components/forms/#forms-controls

2021-09-06 22:51 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                    <a
А зачем было делать это через `<a>`? И с `href`

2021-09-06 22:52 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                        Запись в электронную очередь - это не время, в которое вас будут пускать в
Может уберем тогда вообще, если не знаем какой текст вставить?

2021-09-09 17:48 UTC, idonotknowwhoiam commented on src/forms/Techical.jsx
> +    corpus: yup.number().required().nullable(),
nullable убрал, не знаю зачем он вообще там стоял, случился брейнлаг.

2021-09-09 17:49 UTC, idonotknowwhoiam commented on src/forms/Techical.jsx
> +                        style={{ height: '200px' }}
Исправил, изначально было так, потому что сама библиотека навязывала такой стиль. 

> By default, <textarea>s will be the same height as <input>s. To set a custom height on your <textarea>, do not use the rows attribute. Instead, set an explicit height (either inline or via custom CSS).

2021-09-09 17:50 UTC, idonotknowwhoiam commented on src/pages/Technical/Technical.jsx
> +                    <a
Исправил, изначально было так, потому что я пытался использовать бутстраповскую кнопку и изменить ее в ссылку, но там был баг, который не сбрасывал стили.

2021-09-09 17:50 UTC, idonotknowwhoiam commented on src/pages/Technical/Technical.jsx
> +                        Запись в электронную очередь - это не время, в которое вас будут пускать в
Добавил инструкцию

2021-09-09 22:44 UTC, qqpayne commented on src/forms/Techical.jsx
> +                        style={{ height: '200px' }}
Я думаю они лучше знают, почему луччше использовать явную высоту с `textarea`. По ссылке скинул пример, где они используют `rows`, но уже легитимно, вместе с текстовым полем. Может сделаем как там?

2021-09-19 06:27 UTC, qqpayne requested changes

2021-09-19 06:27 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                        Назад
Можно ли сделать эту надпись и стрелочку чуть больше? Она выглядит супер маленькой на фоне заголовков формы

2021-09-19 06:27 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                        className="d-flex align-items-center mb-2 btn-link border-0 bg-transparent"
На телефоне отступ слева съехал, то есть стрелочка начинается на уровне буквы 'л' в слове 'электронная почта'.

На десктопе все окей при этом, начинается на уровне буквы 'э'.

2021-09-19 06:27 UTC, qqpayne commented on src/forms/Techical.jsx
> +                        Отправить
Что думаешь о том, что бы на телефонах эту кнопку сделать по центру?

2021-09-19 06:27 UTC, qqpayne commented on src/forms/Techical.jsx
> +                    <Form.Label column="lg">Электронная почта:</Form.Label>
С этим полем есть беда на десктопах - оно не очень длинное и при этом не скроллится. Я не вижу ничего после 23 символа.

На телефонах всё ок - там всё скроллится. 

Можно пофиксить просто сделав её чуть длиннее на десктопах, но если ты придумаешь как сделать его скроллабельным - будет пушка.

2021-09-19 06:27 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                    <Row className="gx-5 gy-3 mt-3 mb-1 mt-lg-5 mb-lg-3 justify-content-center">
А `mt-lg-5` точно нужен? 
Имхо без него лучше

`mb-lg-3` можно оставить и даже перенести на все платформы (короче говоря, убрать `mb-lg-3` и `mb-1` и бахнуть `mb-3`)

2021-09-19 06:27 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +        // TODO if feedbackApi.post({ ...values, service }) {...}
Понятное дело с плэйсхолдером мерджить не будем.

Вот набросок спеки на APIшку: https://github.com/CyberDAS-Dev/API/issues/51

Фронту из этого нужен только POST /maintenance. При этом будет авторизация по OTT (не зря же он в #87 сделан был) и нужно будет туда POSTить корпус и комнату, помимо ФИО и эмэйла. Дальше просто POST /maintenance с данными формата `{'text': *описание проблемы из формы*}`

2021-09-19 13:00 UTC, qqpayne commented on src/forms/Techical.jsx
> +                        name="corpus"
Оказалось, что по английски корпус это скорее 'building', чем 'corpus'. 
API будет ожидать именно 'building' в приходящем JSON'е, так что надо поправить

2021-09-20 01:50 UTC, qqpayne commented on src/forms/Techical.jsx
> +                    <Form.Label column="lg">Электронная почта:</Form.Label>
Это у меня что-то багнуло, на самом деле всё ок

2021-09-20 02:10 UTC, qqpayne requested changes

2021-09-20 02:10 UTC, qqpayne commented on src/pages/Technical/Technical.jsx
> +                    <Row className="gx-5 gy-3 mt-3 mb-3 justify-content-center">
Снова докапываюсь до отступов:
```suggestion
                    <Row className="gx-5 gy-3 gy-lg-0 justify-content-center">
```
`mt-3` - не работает, ибо у элемента сверху есть mb-3
`mb-3` - не нужно, ибо элемент в конце страницы, у которой уже по умолчанию есть внутеренний паддинг

`gy-3` добавляет лишние маржины колонкам внутри `<Row>`, и он имеет смысл только на мобильных разрешениях. Поэтому добавил `gy-lg-0`

Так выглядит более аккуратно

2021-09-20 03:59 UTC, qqpayne approved these changes

2021-09-20 04:00 UTC, merged